# Generated by Django 6.1 on 2026-08-15 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CNAE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Imposto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegimeTributario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('razao_social', models.CharField(max_length=200)),
                ('nome_fantasia', models.CharField(blank=True, max_length=200)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('cnae_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cnae')),
                ('impostos', models.ManyToManyField(to='core.imposto')),
                ('regime_tributario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.regimetributario')),
                ('tipo_empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipoempresa')),
            ],
        ),
    ]
