# Generated by Django 5.2 on 2026-08-17 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObrigacaoAcessoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='empresa',
            name='impostos',
            field=models.ManyToManyField(blank=True, to='core.imposto'),
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField()),
                ('mes', models.PositiveSmallIntegerField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencias', to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='ApuracaoImposto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('INFORMADO', 'Informado ao cliente'), ('PAGO', 'Pago'), ('ATRASADO', 'Atrasado'), ('DISPENSADO', 'Dispensado')], default='PENDENTE', max_length=20)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('imposto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apuracoes', to='core.imposto')),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apuracoes_imposto', to='core.competencia')),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='obrigacoes_acessorias',
            field=models.ManyToManyField(blank=True, to='core.obrigacaoacessoria'),
        ),
        migrations.AddConstraint(
            model_name='competencia',
            constraint=models.UniqueConstraint(fields=('empresa', 'ano', 'mes'), name='empresa_competencia_unica'),
        ),
    ]
