# Generated by Django 5.2 on 2026-08-21 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_obrigacaoacessoria_alter_empresa_impostos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CumprimentoObrigacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cumprido', models.BooleanField(default=False)),
                ('data_cumprimento', models.DateField(blank=True, null=True)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cumprimentos_obrigacao', to='core.competencia')),
                ('obrigacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cumprimentos', to='core.obrigacaoacessoria')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('competencia', 'obrigacao'), name='competencia_obrigacao_unica')],
            },
        ),
    ]
