# Generated by Django 6.1 on 2026-08-22 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cumprimentoobrigacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cnae',
            name='dia_vencimento',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Dia do mês em que essa obrigação normalmente vence (ex: 25).', null=True),
        ),
        migrations.AddField(
            model_name='cumprimentoobrigacao',
            name='status_manual',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(3, 'Em dia'), (2, 'Risco de atraso'), (1, 'Atrasada')], help_text='Deixe em branco para o sistema calcular sozinho pela data de vencimento.', null=True),
        ),
    ]
