# Generated by Django 5.2 on 2026-08-22 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cnae_dia_vencimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='obrigacaoacessoria',
            name='dia_vencimento',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Dia do mês em que essa obrigação normalmente vence (ex: 25).', null=True),
        ),
    ]
