# Generated by Django 6.1 on 2026-08-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_obrigacaoacessoria_dia_vencimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cumprimentoobrigacao',
            name='comprovante',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes/%Y/%m/'),
        ),
    ]
