# Generated by Django 6.1 on 2026-08-26 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cumprimentoobrigacao_comprovante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='documentos/%Y/%m/')),
                ('tipo_documento', models.CharField(choices=[('NFE', 'Nota Fiscal'), ('RECIBO_OBRIGACAO', 'Recibo de Obrigação Acessória'), ('BOLETO', 'Boleto'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20)),
                ('cnpj_emitente', models.CharField(blank=True, max_length=18)),
                ('razao_social_emitente', models.CharField(blank=True, max_length=200)),
                ('cnpj_destinatario', models.CharField(blank=True, max_length=18)),
                ('numero_documento', models.CharField(blank=True, max_length=50)),
                ('data_emissao', models.DateField(blank=True, null=True)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('dados_extraidos', models.JSONField(blank=True, default=dict)),
                ('revisado', models.BooleanField(default=False, help_text='Marca se o usuário já conferiu/corrigiu os dados extraídos.')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='core.empresa')),
            ],
        ),
    ]
