# Generated by Django 6.1 on 2026-08-29 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_perfilusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='LancamentoContabil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_lancamento', models.DateField()),
                ('historico', models.CharField(max_length=255)),
                ('conta_debito', models.CharField(blank=True, max_length=100)),
                ('conta_credito', models.CharField(blank=True, max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho — aguardando revisão'), ('CONFIRMADO', 'Confirmado')], default='RASCUNHO', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_confirmacao', models.DateTimeField(blank=True, null=True)),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='core.documento')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='core.empresa')),
            ],
        ),
    ]
