# Generated by Django 6.1 on 2026-08-29 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_lancamentocontabil'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_alerta_certificado', models.PositiveIntegerField(default=30, help_text='Quantos dias antes do vencimento um certificado já deve aparecer em amarelo (próximo a vencer).')),
            ],
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Certificado Digital e-CNPJ A1', max_length=150)),
                ('data_vencimento', models.DateField()),
                ('observacao', models.TextField(blank=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='core.empresa')),
            ],
        ),
    ]
