# Generated by Django 6.1 on 2026-08-30 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_configuracaosistema_certificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='nome_empresa',
            field=models.CharField(blank=True, help_text='Nome do titular do certificado — não precisa estar cadastrado no sistema.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='data_vencimento',
            field=models.DateField(blank=True, help_text='Deixe em branco se ainda não souber a data (aparece para completar depois).', null=True),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Opcional — só selecione se essa empresa já estiver cadastrada.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificados', to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='nome',
            field=models.CharField(blank=True, default='Certificado Digital', help_text='Ex: e-CNPJ A1 (opcional)', max_length=150),
        ),
    ]
