# Generated by Django 6.1 on 2026-08-31 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_certificado_nome_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='certificados/%Y/%m/'),
        ),
    ]
