# Generated by Django 6.1 on 2026-09-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_empresa_cnae_principal_alter_empresa_cnpj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='dias_alerta_imposto',
            field=models.PositiveIntegerField(default=5, help_text='Quantos dias antes do vencimento um imposto já deve aparecer em amarelo.'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='dias_alerta_obrigacao',
            field=models.PositiveIntegerField(default=5, help_text='Quantos dias antes do vencimento uma obrigação já deve aparecer em amarelo.'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='notificacoes_email_ativas',
            field=models.BooleanField(default=False, verbose_name='Alertas por e-mail'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='notificacoes_sistema_ativas',
            field=models.BooleanField(default=True, verbose_name='Notificações dentro do sistema'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='notificar_certificados_proximos',
            field=models.BooleanField(default=True, verbose_name='Certificados próximos a vencer'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='notificar_erros_processamento',
            field=models.BooleanField(default=True, verbose_name='Erros de processamento'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='notificar_obrigacoes_proximas',
            field=models.BooleanField(default=True, verbose_name='Obrigações próximas a vencer'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='notificar_obrigacoes_vencidas',
            field=models.BooleanField(default=True, verbose_name='Obrigações vencidas'),
        ),
    ]
