# Generated by Django 6.1 on 2026-09-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_configuracaosistema_dias_alerta_imposto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=255, unique=True)),
                ('tipo', models.CharField(choices=[('OBRIGACAO_PROXIMA', 'Obrigação próxima a vencer'), ('OBRIGACAO_VENCIDA', 'Obrigação vencida'), ('CERTIFICADO_PROXIMO', 'Certificado próximo a vencer'), ('ERRO_PROCESSAMENTO', 'Erro de processamento')], max_length=30)),
                ('mensagem', models.CharField(max_length=255)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('lida', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='email_notificacoes',
            field=models.EmailField(blank=True, help_text='Endereço que recebe os alertas por e-mail (deixe em branco para não enviar).', max_length=254),
        ),
    ]
