# Generated by Django 6.1 on 2026-09-07 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_notificacao_configuracaosistema_email_notificacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cumprimentoobrigacao',
            name='data_vencimento_manual',
            field=models.DateField(blank=True, null=True),
        ),
    ]
