# Generated by Django 6.1 on 2026-09-10 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_cumprimentoobrigacao_data_vencimento_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cumprimentoobrigacao',
            name='status_manual',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(3, 'Em dia'), (2, 'Risco de atraso'), (1, 'Atrasada'), (4, 'Concluída')], help_text='Deixe em branco para o sistema calcular sozinho pela data de vencimento.', null=True),
        ),
        migrations.AddConstraint(
            model_name='apuracaoimposto',
            constraint=models.UniqueConstraint(fields=('competencia', 'imposto'), name='competencia_imposto_unica'),
        ),
    ]
