# Generated by Django 6.1 on 2026-09-10 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_prevent_duplicate_tax_assessments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cumprimentoobrigacao',
            name='status_manual',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(4, 'Em dia'), (2, 'Risco de atraso'), (1, 'Atrasada'), (3, 'Concluída')], help_text='Deixe em branco para o sistema calcular sozinho pela data de vencimento.', null=True),
        ),
    ]
